### ISSUE TITLE
Reduce the list of requirements

### ISSUE THREAD

**Issue by curiousdannii** [alerque/stack-verse-mapper#5]
This project could probably be accomplished entirely with either Python or Node.js. I like both, but I'm more familiar with Node's npm than whatever the Python equivalent would be.

If @alerque is intending to use the tools he's listed for the initial version that is fine of course, but maybe I could port them to Node bit by bit and we can see which we like more?

**Comment by alerque** [comment]
I'm totally fine with whatever people want to code in. Nodejs is going to be a requirement in order to run the (excelent) BCV parser. Python is probably going to be a good bet for parsing XML and passing  data around to different systems and eventually stuffing it in a database or index of some kind, but if you want to do it in node, I'm fine with that too.

Keep in mind that the requirements liste there only applies to developers wanting to re-build the system from start to finish. Most of the requirements are just tooling to update the index. The actual tool that end users end up running will be much slimmer. I was thinking along the lines of a userscript + sqlite database that could run entirely client-side in somebody's browser. The tooling would really only be required to rebuild a new index when the SE data dump get's refreshed.

**Comment by curiousdannii** [comment]
I think we're both happy with how things are now. We can reevaluate when we start building non-prototype websites/packages.
