### ISSUE TITLE
Keep total count of verse reference per Post and per Question Set

### ISSUE THREAD

**Issue by scottgit** [alerque/stack-verse-mapper#7]
Keeping a total count of a reference mention per Post (Question or Answer) and then cumulative of the Set of a Question and all its set of Answers allows for ranking the extra mentions higher than Posts or Sets that do not have as many.

**Comment by alerque** [comment]
Count per post is going to be easy to factor in. Total count across related posts (question and associated answers) is going to be a lot harder to do correctly, but we can probably fudge a little and get the general effect.

**Comment by curiousdannii** [comment]
Instead of just returning a list of unique references in each post, the index now counts them. So I can report that the post with the most repeated references on Hermeneutics.SE is [this one with 17 references to Revelation 3:14!](http://hermeneutics.stackexchange.com/a/13827/2757)

I have also documented the index structure [in the wiki](https://github.com/alerque/stack-verse-mapper/wiki/Index-structure).
